version: '3'

services:
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    restart: always
